
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import base64
from io import BytesIO
import numpy as np

# 1. Data Generation (Simulating the dataset)
np.random.seed(42)
departments = ['Sales', 'HR', 'R&D', 'Marketing', 'Operations', 'Finance']
regions = ['Europe', 'Latin America', 'Middle East', 'North America', 'Asia']

data = {
    'employee_id': [f'EMP{i:03d}' for i in range(1, 101)],
    'department': np.random.choice(departments, 100),
    'region': np.random.choice(regions, 100),
    'performance_score': np.random.uniform(60, 100, 100).round(2),
    'years_experience': np.random.randint(1, 20, 100),
    'satisfaction_rating': np.random.uniform(3, 5, 100).round(1)
}
df = pd.DataFrame(data)

# 2. Calculate Frequency Count for 'Operations'
ops_count = df[df['department'] == 'Operations'].shape[0]
print(f"Operations Department Count: {ops_count}")

# 3. Create Visualization
plt.figure(figsize=(10, 6))
sns.set_style("whitegrid")
sns.histplot(data=df, x='department', hue='department', shrink=0.8, palette='viridis', legend=False)
plt.title('Distribution of Employees by Department')
plt.xlabel('Department')
plt.ylabel('Frequency')
plt.tight_layout()

# Save plot to base64 string for HTML embedding
buffer = BytesIO()
plt.savefig(buffer, format='png')
buffer.seek(0)
image_base64 = base64.b64encode(buffer.read()).decode('utf-8')
plt.close()

# 4. Generate HTML Report
html_content = f'''
<!DOCTYPE html>
<html>
<head>
    <title>Employee Performance Analysis</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #2c3e50; }}
        .code-block {{ background-color: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; font-family: monospace; }}
        .result {{ font-weight: bold; color: #27ae60; font-size: 1.2em; }}
        .footer {{ margin-top: 50px; font-size: 0.8em; color: #7f8c8d; }}
    </style>
</head>
<body>
    <h1>Employee Performance Analysis Report</h1>
    
    <h2>1. Analysis Output</h2>
    <p>We analyzed the dataset to find the frequency of employees in the <strong>Operations</strong> department:</p>
    <p class="result">Operations Department Count: {ops_count}</p>
    
    <h2>2. Visualization</h2>
    <p>Below is the histogram showing the distribution of employees across all departments:</p>
    <img src="data:image/png;base64,{image_base64}" alt="Department Distribution Histogram">
    
    <h2>3. Source Code</h2>
    <p>The following Python code was used to generate this analysis:</p>
    <div class="code-block">
<pre>
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load/Generate Data
# ... (Data generation code hidden for brevity) ...

# Calculate Operations Count
ops_count = df[df['department'] == 'Operations'].shape[0]
print(f"Operations Department Count: {{ops_count}}")

# Create Histogram
sns.histplot(data=df, x='department')
plt.title('Distribution of Employees by Department')
plt.show()
</pre>
    </div>

    <div class="footer">
        <p>Generated by: 24f1002326@ds.study.iitm.ac.in</p>
        <p>Verification for Employee Performance Analysis Task</p>
    </div>
</body>
</html>
'''

# Write HTML file
with open('analysis_report.html', 'w') as f:
    f.write(html_content)
print("HTML report generated: analysis_report.html")
